name: course

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env: 
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium flask pymysql pypika webdriver_manager
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install chromium and firefox
      run: |
        apt install -y chromium-browser firefox
    - name: run restapp
      run: |
        nohup python rest_app.py $USERNAME $PASSWORD &
    - name: run webapp
      run: |
        nohup python web_app.py $USERNAME $PASSWORD &
    - name: run backend_testing
      run: |
        python backend_testing.py $USERNAME $PASSWORD
    - name: run frontend_testing
      run: |
        python frontend_testing.py $USERNAME $PASSWORD
    - name: run combined_testing
      run: |
        python combined_testing.py $USERNAME $PASSWORD
    - name: run clean_environment
      run: |
        python clean_environment.py
